"""Updated models for Vendor, Sweet, and VendorSweet

Revision ID: bea69b54608b
Revises: ddf6b7190280
Create Date: 2024-10-14 08:18:52.642204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bea69b54608b'
down_revision = 'ddf6b7190280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_sweets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('sweet_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_vendor_sweets_vendor_id_vendors'), 'vendors', ['vendor_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_vendor_sweets_sweet_id_sweets'), 'sweets', ['sweet_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_sweets', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_vendor_sweets_sweet_id_sweets'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_vendor_sweets_vendor_id_vendors'), type_='foreignkey')
        batch_op.drop_column('sweet_id')
        batch_op.drop_column('vendor_id')

    # ### end Alembic commands ###
